- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/master"
  fail_on_prepare_env_warning: true
  resources: "X2LARGE"
  actions:
  - action: "ls"
    type: "BUILD"
    docker_image_name: "library/ubuntu"
    docker_image_tag: "20.04"
    execute_commands:
    - "ls"
    shell: "BASH"
